spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://localhost:3306/db_example'
    username: root
    password: root
#  redis:
#    Host: ${REDIS_HOST:localhost}
#    Port: ${REDIS_PORT:6379}
#    Password:
#    Timeout: 1000ms
#    lettuce:
#      pool:
#        max-active: 16
#        max-idle: 16
#        min-idle: 8
#        max-wait: 1ms
#        time-between-eviction-runs: 9000
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
